name: 'Ideal Homes'
description: 'runs back end'
inputs:
	port-num: 1234
		description: 'port number'
		required: 'true'
outputs:
	time:
		description: 'time server started'
runs:
	using: 'node14'
	main: 'app.js'